-- ==============================================================================
-- PHASE 2: DATABASE AND SECURITY VERIFICATION TEST SUITE
-- ==============================================================================

DO $$
DECLARE
  tables_count integer;
  enums_count integer;
  rls_disabled_count integer;
  row_count integer;
  
  -- Test UIDs
  owner_uid uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  staff_uid uuid := '00000000-0000-0000-0000-000000000002'::uuid;
  kitchen_uid uuid := '00000000-0000-0000-0000-000000000003'::uuid;
  
  -- Entity IDs
  test_category_id uuid := '10000000-0000-0000-0000-000000000001'::uuid;
  test_order_id uuid := '20000000-0000-0000-0000-000000000001'::uuid;
  test_token uuid := '30000000-0000-0000-0000-000000000001'::uuid;
  test_sh_id uuid;
  test_rule_id uuid;
BEGIN
  RAISE NOTICE 'Starting Phase 2 verification checks...';

  -- 1. Clean up any leftover test data
  DELETE FROM public.admin_activity_logs;
  DELETE FROM public.order_items WHERE order_id = test_order_id;
  DELETE FROM public.orders WHERE id = test_order_id;
  DELETE FROM public.categories WHERE id = test_category_id;
  DELETE FROM public.profiles WHERE id IN (owner_uid, staff_uid, kitchen_uid);
  DELETE FROM auth.users WHERE id IN (owner_uid, staff_uid, kitchen_uid);

  -- 2. Verify all 24 tables exist
  SELECT COUNT(*) INTO tables_count FROM information_schema.tables 
  WHERE table_schema = 'public' 
    AND table_name IN (
      'profiles', 'dining_tables', 'reservations', 'reservation_status_events',
      'categories', 'menu_items', 'service_hours', 'holiday_closures',
      'operational_status', 'system_settings', 'contact_inquiries', 'site_content',
      'media_assets', 'delivery_zones', 'delivery_postal_codes', 'delivery_fee_rules',
      'packaging_fee_rules', 'menu_item_packaging_rules', 'orders', 'order_status_events',
      'order_items', 'order_charges', 'notification_logs', 'admin_activity_logs'
    );
  
  IF tables_count = 24 THEN
    RAISE NOTICE '  [PASS] All 24 tables exist successfully.';
  ELSE
    RAISE EXCEPTION '  [FAIL] Expected 24 tables, found %.', tables_count;
  END IF;

  -- 3. Verify all 16 enum types exist
  SELECT COUNT(*) INTO enums_count FROM pg_type t 
  JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public' AND t.typtype = 'e'
    AND t.typname IN (
      'user_role', 'reservation_status', 'reservation_source', 'service_hours_type',
      'affected_service_type', 'inquiry_status', 'order_type', 'order_status',
      'payment_status', 'payment_method', 'packaging_fee_type', 'charge_type',
      'notification_channel', 'notification_status', 'geocoding_status_type', 'rule_action_type'
    );

  IF enums_count = 16 THEN
    RAISE NOTICE '  [PASS] All 16 enum types exist successfully.';
  ELSE
    RAISE EXCEPTION '  [FAIL] Expected 16 enum types, found %.', enums_count;
  END IF;

  -- 4. Verify RLS is enabled on all tables
  SELECT COUNT(*) INTO rls_disabled_count FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r'
    AND c.relname IN (
      'profiles', 'dining_tables', 'reservations', 'reservation_status_events',
      'categories', 'menu_items', 'service_hours', 'holiday_closures',
      'operational_status', 'system_settings', 'contact_inquiries', 'site_content',
      'media_assets', 'delivery_zones', 'delivery_postal_codes', 'delivery_fee_rules',
      'packaging_fee_rules', 'menu_item_packaging_rules', 'orders', 'order_status_events',
      'order_items', 'order_charges', 'notification_logs', 'admin_activity_logs'
    )
    AND NOT c.relrowsecurity;

  IF rls_disabled_count = 0 THEN
    RAISE NOTICE '  [PASS] Row Level Security (RLS) is enabled on all tables.';
  ELSE
    RAISE EXCEPTION '  [FAIL] Found % tables with RLS disabled.', rls_disabled_count;
  END IF;

  -- 5. Set up mock profiles for testing permissions
  -- Insert mock auth users first to avoid FK violations on profiles
  INSERT INTO auth.users (id, email, role, aud)
  VALUES 
    (owner_uid, 'owner@namaste.com', 'authenticated', 'authenticated'),
    (staff_uid, 'staff@namaste.com', 'authenticated', 'authenticated'),
    (kitchen_uid, 'kitchen@namaste.com', 'authenticated', 'authenticated');

  -- Update the profiles generated by the trigger to set correct roles and make active
  UPDATE public.profiles SET role = 'owner'::user_role, full_name = 'Test Owner', phone = '111', is_active = true WHERE id = owner_uid;
  UPDATE public.profiles SET role = 'staff'::user_role, full_name = 'Test Staff', phone = '222', is_active = true WHERE id = staff_uid;
  UPDATE public.profiles SET role = 'kitchen'::user_role, full_name = 'Test Kitchen', phone = '333', is_active = true WHERE id = kitchen_uid;

  -- 6. Test direct RLS SELECT restrictions for public/anon
  -- Set role to anon to simulate public clients
  SET LOCAL role anon;
  
  -- profiles
  SELECT COUNT(*) INTO row_count FROM public.profiles;
  IF row_count > 0 THEN RAISE EXCEPTION 'RLS FAIL: anon can read profiles directamente!'; END IF;
  
  -- orders
  SELECT COUNT(*) INTO row_count FROM public.orders;
  IF row_count > 0 THEN RAISE EXCEPTION 'RLS FAIL: anon can read orders directamente!'; END IF;
  
  -- reservations
  SELECT COUNT(*) INTO row_count FROM public.reservations;
  IF row_count > 0 THEN RAISE EXCEPTION 'RLS FAIL: anon can read reservations directamente!'; END IF;
  
  -- contact_inquiries
  SELECT COUNT(*) INTO row_count FROM public.contact_inquiries;
  IF row_count > 0 THEN RAISE EXCEPTION 'RLS FAIL: anon can read contact_inquiries directamente!'; END IF;
  
  -- notification_logs
  SELECT COUNT(*) INTO row_count FROM public.notification_logs;
  IF row_count > 0 THEN RAISE EXCEPTION 'RLS FAIL: anon can read notification_logs directamente!'; END IF;

  RAISE NOTICE '  [PASS] anon is blocked from reading profiles/orders/reservations/inquiries/notifications.';

  -- 7. Test that public anon can read active categories only
  RESET ROLE;
  INSERT INTO public.categories (id, name_pl, name_en, slug, display_order, is_active, is_deleted)
  VALUES 
    (test_category_id, 'Test PL', 'Test EN', 'test-slug', 1, false, false); -- Inactive category

  SET LOCAL role anon;
  SELECT COUNT(*) INTO row_count FROM public.categories WHERE id = test_category_id;
  IF row_count > 0 THEN 
    RAISE EXCEPTION 'RLS FAIL: anon can see inactive categories!'; 
  ELSE
    RAISE NOTICE '  [PASS] anon can only read active and non-deleted categories.';
  END IF;

  -- 8. Test public RPC functions with wrong token vs correct token
  RESET ROLE;
  -- Insert a test order
  INSERT INTO public.orders (id, customer_name, customer_email, customer_phone, order_type, payment_method, items_subtotal, packaging_total, delivery_fee, other_charges_total, discount_total, total_amount, token, status)
  VALUES (test_order_id, 'Public Customer', 'customer@email.com', '123', 'takeaway', 'cash_on_pickup', 50.00, 2.00, 0.00, 0.00, 0.00, 52.00, test_token, 'pending');

  SET LOCAL role anon;
  -- Wrong token check
  SELECT COUNT(*) INTO row_count FROM public.get_public_order_details_by_token(test_order_id, gen_random_uuid());
  IF row_count > 0 THEN 
    RAISE EXCEPTION 'RPC FAIL: get_public_order_details_by_token returned data for invalid token!';
  ELSE
    RAISE NOTICE '  [PASS] RPC returns zero rows for invalid token.';
  END IF;

  -- Correct token check (Should mask address and return safe fields only)
  SELECT COUNT(*) INTO row_count FROM public.get_public_order_details_by_token(test_order_id, test_token);
  IF row_count = 1 THEN
    RAISE NOTICE '  [PASS] RPC returns exactly one row for valid token.';
  ELSE
    RAISE EXCEPTION 'RPC FAIL: get_public_order_details_by_token failed for valid token!';
  END IF;

  -- 9. Test service hours overlap validation trigger
  RESET ROLE;
  DELETE FROM public.service_hours WHERE service_type = 'dine_in' AND day_of_week = 1;

  INSERT INTO public.service_hours (service_type, day_of_week, slot_number, open_time, close_time, is_closed)
  VALUES ('dine_in', 1, 99, '14:00:00', '16:00:00', false)
  RETURNING id INTO test_sh_id;

  BEGIN
    INSERT INTO public.service_hours (service_type, day_of_week, slot_number, open_time, close_time, is_closed)
    VALUES ('dine_in', 1, 100, '15:00:00', '17:00:00', false);
    
    RAISE EXCEPTION 'FAIL: Service hours overlap trigger failed to block overlapping time windows.';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM LIKE '%Overlapping active service hours%' THEN
      RAISE NOTICE '  [PASS] Service hours overlap trigger successfully blocked overlapping slot.';
    ELSE
      RAISE EXCEPTION 'FAIL: Unexpected error during service hours overlap check: %', SQLERRM;
    END IF;
  END;
  DELETE FROM public.service_hours WHERE id = test_sh_id;

  -- Restore original service hour for day 1
  INSERT INTO public.service_hours (service_type, day_of_week, slot_number, open_time, close_time, is_closed, min_lead_time_minutes, max_preorder_days, display_order)
  VALUES ('dine_in', 1, 1, '12:00:00', '22:00:00', false, 0, 0, 1);

  -- 10. Test delivery fee rules overlap validation trigger (Half-open [min, max) )
  BEGIN
    -- Zone 1 (0 to 2 km) already exists in seed data. Trying to insert [1, 3) should fail.
    INSERT INTO public.delivery_fee_rules (name, min_distance_km, max_distance_km, fee_amount, is_active)
    VALUES ('Overlapping rule test', 1.00, 3.00, 9.99, true);

    RAISE EXCEPTION 'FAIL: Delivery fee rule overlap trigger failed to block overlapping distance rules.';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM LIKE '%Overlapping active delivery fee rules%' THEN
      RAISE NOTICE '  [PASS] Delivery fee overlap trigger successfully blocked overlapping rules.';
    ELSE
      RAISE EXCEPTION 'FAIL: Unexpected error during delivery fee rule overlap check: %', SQLERRM;
    END IF;
  END;

  -- 11. Test staff order update restrictions (cannot update pricing fields)
  -- Mock authentication as staff member
  PERFORM set_config('request.jwt.claims', json_build_object('sub', staff_uid::text)::text, true);
  
  BEGIN
    UPDATE public.orders
    SET items_subtotal = 100.00, total_amount = 102.00
    WHERE id = test_order_id;
    
    RAISE EXCEPTION 'FAIL: Staff was able to update order totals!';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM LIKE '%Staff members are not allowed to modify order pricing%' THEN
      RAISE NOTICE '  [PASS] Staff update protection trigger blocked pricing modification.';
    ELSE
      RAISE EXCEPTION 'FAIL: Unexpected error during staff order update check: %', SQLERRM;
    END IF;
  END;

  -- 12. Test kitchen order update restrictions (cannot update customer/payment/total fields)
  -- Mock authentication as kitchen staff
  PERFORM set_config('request.jwt.claims', json_build_object('sub', kitchen_uid::text)::text, true);
  
  BEGIN
    UPDATE public.orders
    SET customer_name = 'Hacked Name'
    WHERE id = test_order_id;
    
    RAISE EXCEPTION 'FAIL: Kitchen was able to update order customer details!';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM LIKE '%Kitchen staff is only allowed to update order status%' THEN
      RAISE NOTICE '  [PASS] Kitchen update protection trigger blocked customer detail modification.';
    ELSE
      RAISE EXCEPTION 'FAIL: Unexpected error during kitchen order update check: %', SQLERRM;
    END IF;
  END;

  -- 13. Test owner logs select vs manager/staff
  RESET ROLE;
  INSERT INTO public.admin_activity_logs (admin_id, action, details)
  VALUES (staff_uid, 'Test Action', '{}'::jsonb);

  -- Owner select check
  SET LOCAL role authenticated;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', owner_uid::text)::text, true);
  SELECT COUNT(*) INTO row_count FROM public.admin_activity_logs;
  IF row_count = 1 THEN
    RAISE NOTICE '  [PASS] Owner can read admin activity logs successfully.';
  ELSE
    RAISE EXCEPTION 'RLS FAIL: Owner cannot read admin logs!';
  END IF;

  -- Staff select check (should be blocked)
  SET LOCAL role authenticated;
  PERFORM set_config('request.jwt.claims', json_build_object('sub', staff_uid::text)::text, true);
  SELECT COUNT(*) INTO row_count FROM public.admin_activity_logs;
  IF row_count > 0 THEN
    RAISE EXCEPTION 'RLS FAIL: Staff can read admin activity logs!';
  ELSE
    RAISE NOTICE '  [PASS] Staff cannot read admin activity logs.';
  END IF;

  -- Admin logs update/delete check (should be blocked for everyone)
  RESET ROLE;
  BEGIN
    SET LOCAL role authenticated;
    PERFORM set_config('request.jwt.claims', json_build_object('sub', owner_uid::text)::text, true);
    UPDATE public.admin_activity_logs SET action = 'tampered' WHERE admin_id = staff_uid;
    GET DIAGNOSTICS row_count = ROW_COUNT;
    IF row_count > 0 THEN
      RAISE EXCEPTION 'RLS FAIL: Owner was able to update admin logs directly!';
    ELSE
      RAISE NOTICE '  [PASS] Admin logs cannot be updated directly.';
    END IF;
  END;

  -- Clean up
  RESET ROLE;
  DELETE FROM public.admin_activity_logs;
  DELETE FROM public.order_items WHERE order_id = test_order_id;
  DELETE FROM public.orders WHERE id = test_order_id;
  DELETE FROM public.categories WHERE id = test_category_id;
  DELETE FROM public.profiles WHERE id IN (owner_uid, staff_uid, kitchen_uid);
  DELETE FROM auth.users WHERE id IN (owner_uid, staff_uid, kitchen_uid);

  RAISE NOTICE 'All Phase 2 verification checks passed successfully!';
END;
$$;
